import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  allSidebar: [{ type: 'autogenerated', dirName: '.' }],
  
  // Default sidebar for the main docs (if you're still using it)
  temporarySidebar: [{ type: 'autogenerated', dirName: 'temporary' }],

  // Sidebar for Initiative Management docs
  initiativesSidebar: [{ type: 'autogenerated', dirName: 'initiatives' }],

  // Sidebar for Organization Management docs
  organizationSidebar: [{ type: 'autogenerated', dirName: 'organization' }],

  // Sidebar for Event Management docs
  eventsSidebar: [{ type: 'autogenerated', dirName: 'events' }],

  // Sidebar for Event Management docs
  developmentSidebar: [{ type: 'autogenerated', dirName: 'development' }],

  // Sidebar for Guide docs
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
};

export default sidebars;
